<?php

declare(strict_types=1);

namespace SatelliteWP\Xtractor\Crm;

use PDO;

/**
 * Query layer over the external CRM/billing database: clients, subscriptions,
 * products (licenses/maintenance plans), websites, their tags and their items
 * (plugins/themes). Almost entirely read-only — the sync that populates it
 * runs elsewhere — with **one deliberate exception**: setSubscriptionWebsite()
 * (2026-09-02, user request) lets an operator fix which website a
 * subscription is linked to, since that link is sometimes missing or wrong
 * and nothing else corrects it. If `swp_subscriptions_websites` turns out to
 * be regenerated by the same external sync, a manual fix here could be
 * overwritten on the next run — worth confirming with whoever owns that sync.
 *
 * Every query here is written in portable SQL (plain JOIN/subquery/LIKE, no
 * MySQL-only syntax like GROUP_CONCAT's SEPARATOR keyword, CURRENT_TIMESTAMP
 * instead of MySQL's NOW()) so the exact same class can be tested against a
 * SQLite fixture without a real MySQL server — see
 * tests/Crm/ClientsRepositoryTest.php. Aggregating tags/client names per
 * website is therefore done with a second query + a PHP merge instead of
 * GROUP_CONCAT, which is not portable between the two engines.
 */
final class ClientsRepository
{
    public const string PRODUCT_TYPE_LICENSE          = 'license';
    public const string PRODUCT_TYPE_MAINTENANCE_PLAN = 'maintenance_plan';
    public const string PRODUCT_TYPE_OTHER            = 'other';

    public function __construct(private readonly PDO $pdo)
    {
    }

    /**
     * A display name for a client row: company, else first+last name, else the email.
     *
     * @param array<string, mixed> $client
     */
    public static function clientLabel(array $client): string
    {
        $company = trim((string) ($client['company'] ?? ''));
        if ($company !== '') {
            return $company;
        }

        $name = trim(trim((string) ($client['first_name'] ?? '')) . ' ' . trim((string) ($client['last_name'] ?? '')));
        if ($name !== '') {
            return $name;
        }

        return (string) ($client['email'] ?? '');
    }

    // ---- Clients -----------------------------------------------------

    /**
     * @param string|null $serviceFilter 'active' (>=1 active subscription),
     *        'inactive' (no active subscription — pending/on-hold/none),
     *        or null/'' for every client
     * @param string|null $search matched against company/first name/last
     *        name/email (LIKE, case-insensitive)
     * @param string|null $subscriptionFilter 'have_unassigned' (>=1
     *        subscription with no linked website), 'no_unassigned' (every
     *        subscription is linked, or the client has none at all), or
     *        null/'' for every client
     * @return list<array<string, mixed>>
     */
    public function listClients(
        ?string $serviceFilter = null,
        ?string $search = null,
        ?string $subscriptionFilter = null,
    ): array {
        $where  = [];
        $params = [];
        if ($search !== null && $search !== '') {
            $where[]     = '(c.company LIKE :q OR c.first_name LIKE :q OR c.last_name LIKE :q OR c.email LIKE :q)';
            $params['q'] = '%' . $search . '%';
        }

        $sql = <<<'SQL'
            SELECT c.*,
                   (SELECT COUNT(*) FROM swp_subscriptions s WHERE s.client_id = c.id) AS subscription_count,
                   (SELECT COUNT(DISTINCT sw.website_id)
                      FROM swp_subscriptions s
                      JOIN swp_subscriptions_websites sw ON sw.subscription_id = s.id
                     WHERE s.client_id = c.id) AS website_count,
                   (SELECT COUNT(*) FROM swp_subscriptions s
                     WHERE s.client_id = c.id AND s.subscription_status = 'active') AS active_subscription_count,
                   (SELECT COUNT(*) FROM swp_subscriptions s
                      LEFT JOIN swp_subscriptions_websites sw ON sw.subscription_id = s.id
                     WHERE s.client_id = c.id AND sw.website_id IS NULL) AS orphan_subscription_count
            FROM swp_clients c
            SQL;
        if ($where !== []) {
            $sql .= ' WHERE ' . implode(' AND ', $where);
        }
        $sql .= ' ORDER BY c.company, c.last_name, c.first_name';

        $stmt = $this->pdo->prepare($sql);
        $stmt->execute($params);
        $rows = $stmt->fetchAll();

        if ($serviceFilter === 'active') {
            $rows = array_values(array_filter($rows, static fn (array $r): bool => (int) $r['active_subscription_count'] > 0));
        } elseif ($serviceFilter === 'inactive') {
            $rows = array_values(array_filter($rows, static fn (array $r): bool => (int) $r['active_subscription_count'] === 0));
        }

        if ($subscriptionFilter === 'have_unassigned') {
            $rows = array_values(array_filter($rows, static fn (array $r): bool => (int) $r['orphan_subscription_count'] > 0));
        } elseif ($subscriptionFilter === 'no_unassigned') {
            $rows = array_values(array_filter($rows, static fn (array $r): bool => (int) $r['orphan_subscription_count'] === 0));
        }

        return $rows;
    }

    /**
     * Most recent `date_sync` across the whole clients table — a page-level
     * freshness indicator ("last synced 50 minutes ago"), not a per-client
     * fact.
     */
    public function clientsLastSyncedAt(): ?string
    {
        $value = $this->pdo->query('SELECT MAX(date_sync) FROM swp_clients')->fetchColumn();

        return is_string($value) && $value !== '' ? $value : null;
    }

    /**
     * How many subscriptions (across every client, regardless of the
     * current filter) have no linked website at all — checked unconditionally
     * on every /clients page load so the warning banner can appear even
     * when the operator isn't already filtering for it (2026-09-02, user:
     * "on fait toujours une requête pour valider si des subscriptions ne
     * sont pas liées").
     */
    public function countOrphanSubscriptions(): int
    {
        return (int) $this->pdo->query(<<<'SQL'
            SELECT COUNT(*) FROM swp_subscriptions s
            LEFT JOIN swp_subscriptions_websites sw ON sw.subscription_id = s.id
            WHERE sw.website_id IS NULL
            SQL)->fetchColumn();
    }

    /** @return array<string, mixed>|null */
    public function getClient(int $id): ?array
    {
        $stmt = $this->pdo->prepare('SELECT * FROM swp_clients WHERE id = :id');
        $stmt->execute(['id' => $id]);
        $row = $stmt->fetch();

        return $row === false ? null : $row;
    }

    /**
     * Every subscription for a client, with its product and (if any) the one
     * website it is linked to.
     *
     * @return list<array<string, mixed>>
     */
    public function subscriptionsForClient(int $clientId): array
    {
        $stmt = $this->pdo->prepare(<<<'SQL'
            SELECT s.*,
                   p.name AS product_name, p.category AS product_category,
                   l.slug AS license_slug,
                   sw.website_id AS website_id, w.url AS website_url
            FROM swp_subscriptions s
            JOIN swp_products p ON p.id = s.product_id
            LEFT JOIN swp_licenses l ON l.auto_id = p.auto_id
            LEFT JOIN swp_subscriptions_websites sw ON sw.subscription_id = s.id
            LEFT JOIN swp_websites w ON w.id = sw.website_id
            WHERE s.client_id = :client_id
            ORDER BY s.creation_date DESC
            SQL);
        $stmt->execute(['client_id' => $clientId]);

        return $stmt->fetchAll();
    }

    // ---- Websites ------------------------------------------------------

    /**
     * @param list<string>|null $tags OR-matched: a website carrying at least
     *        one of these tags is included (not required to carry all of them)
     * @param string|null $connectionStatus exact match, e.g. 'CONNECTED' / 'DISCONNECTED'
     * @return list<array<string, mixed>> each row carries 'tags' (list<string>)
     */
    public function listWebsites(
        ?array $tags = null,
        ?int $clientId = null,
        ?string $search = null,
        ?string $connectionStatus = null,
    ): array {
        $where  = [];
        $params = [];

        if ($clientId !== null) {
            $where[]            = 'w.id IN (
                SELECT sw.website_id FROM swp_subscriptions_websites sw
                JOIN swp_subscriptions s ON s.id = sw.subscription_id
                WHERE s.client_id = :client_id
            )';
            $params['client_id'] = $clientId;
        }
        if ($tags !== null && $tags !== []) {
            $placeholders = [];
            foreach ($tags as $i => $tag) {
                $name                = 'tag' . $i;
                $placeholders[]      = ':' . $name;
                $params[$name]       = $tag;
            }
            $where[] = 'w.id IN (SELECT website_id FROM swp_website_tags WHERE tag IN (' . implode(',', $placeholders) . '))';
        }
        if ($search !== null && $search !== '') {
            $where[]     = '(w.url LIKE :q OR w.host LIKE :q)';
            $params['q'] = '%' . $search . '%';
        }
        if ($connectionStatus !== null && $connectionStatus !== '') {
            $where[]                       = 'w.connection_status = :connection_status';
            $params['connection_status']   = $connectionStatus;
        }

        $sql = 'SELECT w.* FROM swp_websites w';
        if ($where !== []) {
            $sql .= ' WHERE ' . implode(' AND ', $where);
        }
        $sql .= ' ORDER BY w.url';

        $stmt = $this->pdo->prepare($sql);
        $stmt->execute($params);
        $websites = $stmt->fetchAll();

        if ($websites === []) {
            return [];
        }

        $ids           = array_map(static fn (array $w): int => (int) $w['id'], $websites);
        $tagsByWebsite = $this->tagsByWebsiteIds($ids);

        foreach ($websites as &$website) {
            $website['tags'] = $tagsByWebsite[(int) $website['id']] ?? [];
        }

        return $websites;
    }

    /** @return array<string, mixed>|null carries 'tags' (list<string>) */
    public function getWebsite(int $id): ?array
    {
        $stmt = $this->pdo->prepare('SELECT * FROM swp_websites WHERE id = :id');
        $stmt->execute(['id' => $id]);
        $row = $stmt->fetch();
        if ($row === false) {
            return null;
        }

        $row['tags'] = $this->tagsByWebsiteIds([$id])[$id] ?? [];

        return $row;
    }

    /**
     * Every subscription (and its client) linked to a website.
     *
     * @return list<array<string, mixed>>
     */
    public function subscriptionsForWebsite(int $websiteId): array
    {
        $stmt = $this->pdo->prepare(<<<'SQL'
            SELECT s.*,
                   p.name AS product_name, p.category AS product_category,
                   l.slug AS license_slug,
                   c.id AS client_id, c.email AS client_email,
                   c.first_name, c.last_name, c.company
            FROM swp_subscriptions_websites sw
            JOIN swp_subscriptions s ON s.id = sw.subscription_id
            JOIN swp_products p ON p.id = s.product_id
            LEFT JOIN swp_licenses l ON l.auto_id = p.auto_id
            JOIN swp_clients c ON c.id = s.client_id
            WHERE sw.website_id = :website_id
            ORDER BY s.creation_date DESC
            SQL);
        $stmt->execute(['website_id' => $websiteId]);

        return $stmt->fetchAll();
    }

    /**
     * A website's items, split the way the UI wants them: plugins and themes
     * called out explicitly, anything else (a future item type) bucketed
     * separately rather than silently dropped.
     *
     * @return array{plugin: list<array<string,mixed>>, theme: list<array<string,mixed>>, other: list<array<string,mixed>>}
     */
    public function itemsForWebsite(int $websiteId): array
    {
        $stmt = $this->pdo->prepare('SELECT * FROM swp_website_items WHERE website_id = :id ORDER BY name');
        $stmt->execute(['id' => $websiteId]);

        $grouped = ['plugin' => [], 'theme' => [], 'other' => []];
        foreach ($stmt->fetchAll() as $row) {
            $type              = strtolower((string) ($row['type'] ?? ''));
            $bucket            = in_array($type, ['plugin', 'theme'], true) ? $type : 'other';
            $grouped[$bucket][] = $row;
        }

        return $grouped;
    }

    /**
     * Distinct tags matching $query — backs the select2 AJAX source for the
     * /websites tag filter (2026-09-02: that filter used to preload every
     * tag into the page; with 315 clients and ~100 websites elsewhere in
     * this database, "preload everything, filter client-side" does not
     * scale as a general pattern, so every select2 here — including this
     * one, small as it is today — searches the server instead).
     *
     * @return list<string>
     */
    public function searchTags(string $query, int $limit = 50): array
    {
        $stmt = $this->pdo->prepare(
            'SELECT DISTINCT tag FROM swp_website_tags WHERE tag LIKE :q ORDER BY tag LIMIT :limit'
        );
        $stmt->bindValue('q', '%' . $query . '%');
        $stmt->bindValue('limit', $limit, PDO::PARAM_INT);
        $stmt->execute();

        return array_column($stmt->fetchAll(), 'tag');
    }

    /**
     * Clients matching $query (email/name/company) — backs the select2 AJAX
     * source for the /websites client filter.
     *
     * @return list<array{id:int,label:string}>
     */
    public function searchClients(string $query, int $limit = 50): array
    {
        $stmt = $this->pdo->prepare(<<<'SQL'
            SELECT id, email, first_name, last_name, company FROM swp_clients
            WHERE email LIKE :q OR first_name LIKE :q OR last_name LIKE :q OR company LIKE :q
            ORDER BY company, last_name, first_name
            LIMIT :limit
            SQL);
        $stmt->bindValue('q', '%' . $query . '%');
        $stmt->bindValue('limit', $limit, PDO::PARAM_INT);
        $stmt->execute();

        return array_map(
            static fn (array $c): array => ['id' => (int) $c['id'], 'label' => self::clientLabel($c)],
            $stmt->fetchAll()
        );
    }

    /**
     * @param list<int> $websiteIds
     * @return array<int, list<string>>
     */
    private function tagsByWebsiteIds(array $websiteIds): array
    {
        if ($websiteIds === []) {
            return [];
        }

        $placeholders = implode(',', array_fill(0, count($websiteIds), '?'));
        $stmt         = $this->pdo->prepare(
            "SELECT website_id, tag FROM swp_website_tags WHERE website_id IN ({$placeholders}) ORDER BY tag"
        );
        $stmt->execute($websiteIds);

        $result = [];
        foreach ($stmt->fetchAll() as $row) {
            $result[(int) $row['website_id']][] = (string) $row['tag'];
        }

        return $result;
    }

    /**
     * The client(s) linked to a website via any of its subscriptions — for
     * the website detail page's "who is the client" section (usually one,
     * but nothing in the schema guarantees every subscription on a site
     * belongs to the same client, so this is a list).
     *
     * @return list<array<string, mixed>> full swp_clients rows (id, company, first_name, last_name, email, ...)
     */
    public function clientsForWebsite(int $websiteId): array
    {
        $stmt = $this->pdo->prepare(<<<'SQL'
            SELECT DISTINCT c.*
            FROM swp_subscriptions_websites sw
            JOIN swp_subscriptions s ON s.id = sw.subscription_id
            JOIN swp_clients c ON c.id = s.client_id
            WHERE sw.website_id = :website_id
            ORDER BY c.company, c.last_name, c.first_name
            SQL);
        $stmt->execute(['website_id' => $websiteId]);

        return $stmt->fetchAll();
    }

    // ---- Subscription <-> website assignment (the one write path) --------

    /**
     * A "DEV" tag marks a dev/staging copy, not a real client site — a
     * subscription should never be pointed at one (2026-09-02, user: "La
     * liste des sites doit exclure les sites ayant le tag 'dev'"; confirmed
     * live against the real table that the tag is spelled exactly "DEV").
     */
    public const string TAG_EXCLUDED_FROM_ASSIGNMENT = 'DEV';

    /**
     * Websites a subscription may be assigned to: every website except one
     * tagged TAG_EXCLUDED_FROM_ASSIGNMENT. The full, unfiltered list — used
     * only for setSubscriptionWebsite()'s server-side validation, never
     * rendered directly (see searchAssignableWebsites() for that).
     *
     * @return list<array{id:int,url:string}>
     */
    public function assignableWebsites(): array
    {
        $stmt = $this->pdo->prepare(<<<'SQL'
            SELECT id, url FROM swp_websites
            WHERE id NOT IN (SELECT website_id FROM swp_website_tags WHERE tag = :tag)
            ORDER BY url
            SQL);
        $stmt->execute(['tag' => self::TAG_EXCLUDED_FROM_ASSIGNMENT]);

        return $stmt->fetchAll();
    }

    /**
     * Assignable websites matching $query — backs the select2 AJAX source
     * for the "linked website" control on a subscription
     * (subscription_website_form() in helpers.php).
     *
     * @return list<array{id:int,url:string}>
     */
    public function searchAssignableWebsites(string $query, int $limit = 50): array
    {
        $stmt = $this->pdo->prepare(<<<'SQL'
            SELECT id, url FROM swp_websites
            WHERE id NOT IN (SELECT website_id FROM swp_website_tags WHERE tag = :tag)
              AND url LIKE :q
            ORDER BY url
            LIMIT :limit
            SQL);
        $stmt->bindValue('tag', self::TAG_EXCLUDED_FROM_ASSIGNMENT);
        $stmt->bindValue('q', '%' . $query . '%');
        $stmt->bindValue('limit', $limit, PDO::PARAM_INT);
        $stmt->execute();

        return $stmt->fetchAll();
    }

    /**
     * Changes (or clears, when $websiteId is null) which website a
     * subscription is linked to. Always a delete-then-insert, never an
     * update-in-place: relinking a subscription is a new fact ("this
     * website, as of today"), not a correction of the old link's own
     * `date_added` — and a delete+insert is the one operation both MySQL and
     * SQLite express identically (an upsert would need MySQL's
     * `ON DUPLICATE KEY UPDATE` vs. SQLite's `ON CONFLICT ... DO UPDATE`,
     * which are not portable).
     *
     * @return bool false when the subscription does not exist, or the target
     *              website does not exist or is excluded from assignment
     */
    public function setSubscriptionWebsite(int $subscriptionId, ?int $websiteId): bool
    {
        $subStmt = $this->pdo->prepare('SELECT 1 FROM swp_subscriptions WHERE id = :id');
        $subStmt->execute(['id' => $subscriptionId]);
        if ($subStmt->fetchColumn() === false) {
            return false;
        }

        if ($websiteId !== null && !in_array($websiteId, array_column($this->assignableWebsites(), 'id'), true)) {
            return false;
        }

        $this->pdo->beginTransaction();
        try {
            $this->pdo->prepare('DELETE FROM swp_subscriptions_websites WHERE subscription_id = :id')
                ->execute(['id' => $subscriptionId]);

            if ($websiteId !== null) {
                $this->pdo->prepare(<<<'SQL'
                    INSERT INTO swp_subscriptions_websites (subscription_id, website_id, date_added, date_updated)
                    VALUES (:sub, :web, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                    SQL)->execute(['sub' => $subscriptionId, 'web' => $websiteId]);
            }

            $this->pdo->commit();
        } catch (\PDOException $e) {
            $this->pdo->rollBack();
            throw $e;
        }

        return true;
    }

    // ---- Products --------------------------------------------------------

    /**
     * Every product, with its derived type: a product is a 'license' or a
     * 'maintenance_plan' exactly when it has a matching row in that child
     * table (by auto_id) — not a free-text 'category' column, which is not
     * guaranteed to only ever hold these two values plus "other".
     *
     * @param string|null $type one of the PRODUCT_TYPE_* constants to filter by; null/'' for every product
     * @return list<array<string, mixed>>
     */
    public function listProducts(?string $type = null): array
    {
        $rows = $this->pdo->query(<<<'SQL'
            SELECT p.*,
                   l.slug AS license_slug, l.type AS license_type, l.is_manual_update,
                   mp.is_licenses_included,
                   CASE
                       WHEN l.auto_id IS NOT NULL THEN 'license'
                       WHEN mp.auto_id IS NOT NULL THEN 'maintenance_plan'
                       ELSE 'other'
                   END AS product_type
            FROM swp_products p
            LEFT JOIN swp_licenses l ON l.auto_id = p.auto_id
            LEFT JOIN swp_maintenance_plans mp ON mp.auto_id = p.auto_id
            ORDER BY p.name
            SQL)->fetchAll();

        if ($type === null || $type === '') {
            return $rows;
        }

        return array_values(array_filter($rows, static fn (array $r): bool => $r['product_type'] === $type));
    }

    // ---- Items (cross-site plugin/theme browser) --------------------------

    /** @return list<string> */
    public function distinctItemTypes(): array
    {
        return array_column(
            $this->pdo->query('SELECT DISTINCT type FROM swp_website_items ORDER BY type')->fetchAll(),
            'type'
        );
    }

    /**
     * "Which sites have which plugins": a filterable, paginated cross-site
     * browse of every item, joined to its website's URL for context.
     *
     * @param array{type?: string, q?: string, vulnerable?: bool, updateAvailable?: bool} $filters
     * @return array{total: int, filtered: int, rows: list<array<string, mixed>>}
     */
    public function searchItems(array $filters, int $offset, int $limit): array
    {
        $where  = [];
        $params = [];

        $type = (string) ($filters['type'] ?? '');
        if ($type !== '') {
            $where[]        = 'i.type = :type';
            $params['type'] = $type;
        }
        if (!empty($filters['vulnerable'])) {
            $where[] = 'i.is_vulnerable = 1';
        }
        if (!empty($filters['updateAvailable'])) {
            $where[] = 'i.is_update_available = 1';
        }
        $q = trim((string) ($filters['q'] ?? ''));
        if ($q !== '') {
            $where[]     = '(i.name LIKE :q OR i.slug LIKE :q OR w.url LIKE :q)';
            $params['q'] = '%' . $q . '%';
        }

        $whereSql = $where !== [] ? 'WHERE ' . implode(' AND ', $where) : '';

        $total = (int) $this->pdo->query('SELECT COUNT(*) FROM swp_website_items')->fetchColumn();

        $countStmt = $this->pdo->prepare(
            "SELECT COUNT(*) FROM swp_website_items i JOIN swp_websites w ON w.id = i.website_id {$whereSql}"
        );
        $countStmt->execute($params);
        $filtered = (int) $countStmt->fetchColumn();

        $stmt = $this->pdo->prepare(<<<SQL
            SELECT i.*, w.url AS website_url
            FROM swp_website_items i
            JOIN swp_websites w ON w.id = i.website_id
            {$whereSql}
            ORDER BY i.name ASC
            LIMIT :limit OFFSET :offset
            SQL);
        foreach ($params as $key => $value) {
            $stmt->bindValue($key, $value);
        }
        $stmt->bindValue('limit', $limit, PDO::PARAM_INT);
        $stmt->bindValue('offset', $offset, PDO::PARAM_INT);
        $stmt->execute();

        return ['total' => $total, 'filtered' => $filtered, 'rows' => $stmt->fetchAll()];
    }
}
